pos 0 ART pos 1 ART => PREP
pos -1 V pos 0 PRO-KS-REL => KS
pos -1 NPROP pos 0 N => NPROP
pos -1 NPROP pos 0 NPROP pos 1 : => N
pos -1 PROPESS pos 0 N => V
pos -1 NPROP pos 0 PREP pos 1 NPROP => NPROP
pos -1 CUR pos 0 N => NUM
pos 0 ART pos 1 V => PREP
pos 0 VAUX pos 1 ART => V
pos 0 ART pos 1 PREP => PROSUB
pos -1 PRO-KS-REL pos 0 N => V
pos 0 ART pos 1 PRO-KS-REL => PROSUB
pos -1 VAUX pos 0 N => PCP
pos 0 PRO-KS-REL pos 1 ART => KS
pos 0 V pos 1 PCP => VAUX
pos -1 ART pos 0 ADJ pos 1 PREP => N
pos 0 VAUX pos 1 PREP => V
pos -1 , pos 0 N pos 1 ART => V
pos -1 N pos 0 N pos 1 NPROP => NPROP
pos 0 VAUX pos 1 ADJ => V
pos -1 N pos 0 N pos 1 ART => V
pos -1 N pos 0 NUM => N
pos -1 " pos 1 NPROP => NPROP
pos 0 PROADJ pos 1 V => PROSUB
pos -1 ADV pos 0 PRO-KS-REL => KS
pos 0 PROADJ pos 1 , => PROSUB
pos -1 , pos 0 PREP pos 1 PDEN => PDEN
pos -1 ART pos 0 ADJ pos 1 V => N
pos -1 ADV pos 0 N pos 1 ART => V
pos 0 ART pos 1 VAUX => PREP
pos -1 PREP pos 0 NUM pos 1 PREP => N
pos 0 PROADJ pos 1 PREP => PROSUB
pos -1 ART pos 0 ADJ pos 1 , => N
pos -1 KC pos 0 N pos 1 ART => V
pos 0 PROADJ pos 1 . => PROSUB
pos -1 PREP pos 0 PRO-KS-REL => KS
pos 0 ART pos 1 PROPESS => PREP
pos -1 ART pos 0 ADJ pos 1 . => N
pos -1 NPROP pos 0 PRO-KS-REL => KS
pos 0 VAUX pos 1 ADV => V
pos -1 , pos 0 N pos 1 PROPESS => V
pos -1 PROSUB pos 0 KS pos 1 ART => PRO-KS-REL
pos -1 ADJ pos 0 NPROP pos 1 KS => KS
pos -1 , pos 0 N pos 1 NPROP => NPROP
pos -1 N pos 0 N pos 1 KC => ADJ
pos 0 N pos 1 PROADJ => V
pos -1 ART pos 0 V pos 1 PROADJ => N
pos 0 ART pos 1 CUR => PREP
pos -1 N pos 0 NPROP pos 1 KS => KS
pos -1 PREP pos 0 N pos 1 NPROP => NPROP
pos -1 " pos 0 N pos 1 ART => V
pos 0 PROADJ pos 1 PRO-KS-REL => PROSUB
pos -1 NPROP pos 0 PREP pos 1 NPROP => NPROP
pos -1 , pos 0 ADV pos 1 KS => KS
pos -1 PRO-KS-REL pos 0 PREP pos 1 V => PROPESS
pos -1 KS pos 0 N pos 1 ART => V
pos -1 PREP pos 0 NUM pos 1 , => N
pos -1 NPROP pos 0 N pos 1 , => NPROP
pos 0 PREP pos 1 , => ADV
pos -1 ART pos 0 PCP => N
pos -1 NUM pos 0 ART pos 1 NUM => PREP
pos -1 N pos 0 N pos 1 ( => NPROP
pos -1 NPROP pos 0 N pos 1 " => NPROP
pos -1 ADV pos 0 NPROP pos 1 KS => KS
pos -1 PREP pos 0 NUM pos 1 . => N
pos -1 N pos 0 N pos 1 PROPESS => V
pos 0 VAUX pos 1 PROADJ => V
pos 0 V pos 1 VAUX => VAUX
pos -1 PREP pos 0 ADJ pos 1 PREP => N
pos -1 N pos 0 N pos 1 PRO-KS-REL => ADJ
pos -1 N pos 0 ART pos 1 NUM => PREP
pos -1 NPROP pos 0 KS pos 1 V => PRO-KS-REL
pos 0 PRO-KS-REL pos 1 PROADJ => KS
pos -1 V pos 0 PROSUB pos 1 PRO-KS-REL => PRO-KS
pos -1 PRO-KS pos 0 PRO-KS-REL => PRO-KS
pos -1 , pos 0 PROSUB pos 1 PRO-KS-REL => PRO-KS
pos -1 PREP pos 0 ADJ pos 1 , => N
pos -1 N pos 0 N pos 1 " => NPROP
pos -1 N pos 0 N pos 1 NPROP => NPROP
pos -1 NPROP pos 0 N pos 1 NPROP => NPROP
pos -1 KC pos 0 N pos 1 NPROP => NPROP
pos -1 ART pos 0 ADJ pos 1 PRO-KS-REL => N
pos -1 VAUX pos 0 PRO-KS-REL => KS
pos -1 PDEN pos 0 PRO-KS-REL => KS
pos 0 VAUX pos 1 , => V
pos -1 KC pos 0 NUM pos 1 PREP => N
pos -1 ADV pos 0 N pos 1 , => ADJ
pos -1 N pos 0 PROSUB pos 1 PREP => PREP
pos -1 , pos 0 PROPESS pos 1 ART => KS
pos 0 VAUX pos 1 NPROP => V
pos -1 ADV pos 0 N pos 1 N => V
pos 0 PROADJ pos 1 ADV => PROSUB
pos -1 PROPESS pos 0 PROSUB => PROADJ
pos -1 PDEN pos 0 ADV pos 1 NUM => PDEN
pos 0 PROADJ pos 1 VAUX => PROSUB
pos 0 VAUX pos 1 NUM => V
pos -1 ART pos 0 NUM pos 1 V => N
pos -1 ART pos 0 ADJ pos 1 ADV => N
pos -1 PRO-KS pos 0 N => V
pos -1 ART pos 0 ADJ pos 1 VAUX => N
pos 0 PRO-KS-REL pos 1 PROSUB => KS
pos 0 PROSUB pos 1 PROSUB => PROADJ
pos -1 PDEN pos 0 N pos 1 ART => V
pos -1 N pos 0 ART pos 1 PROADJ => PREP
pos -1 PREP pos 0 NUM pos 1 ART => N
pos -1 PROPESS pos 0 PRO-KS-REL => KS
pos 0 VAUX pos 1 . => V
pos -1 ART pos 0 NUM pos 1 PREP => N
pos -1 ART pos 0 ADJ pos 1 : => N
pos -1 PRO-KS pos 0 PRO-KS-REL => PRO-KS
pos 0 PREP pos 1 . => ADV
pos -1 PREP pos 0 NUM pos 1 PREP => N
pos -1 KC pos 0 NUM pos 1 , => N
pos -1 ART pos 0 ADJ pos 1 KC => N
pos -1 ART pos 0 PDEN pos 1 PREP => N
pos 0 VAUX pos 1 PROSUB => V
pos -1 ( pos 0 N pos 1 NPROP => NPROP
pos 0 NUM pos 1 VAUX => N
pos -1 V pos 0 ART pos 1 V => PREP
pos -1 PREP pos 0 ADJ pos 1 . => N
pos -1 NPROP pos 0 NPROP pos 1 PROADJ => V
pos -1 KC pos 0 V pos 1 , => PDEN
pos -1 , pos 0 NUM pos 1 PREP => N
pos -1 N pos 0 PROSUB pos 1 . => PROADJ
pos -1 ART pos 0 NUM pos 1 . => N
pos -1 PROADJ pos 0 V pos 1 PROADJ => N
pos -1 ADJ pos 0 ART pos 1 PROADJ => PREP
pos -1 " pos 0 N pos 1 N => NPROP
pos -1 N pos 0 PROSUB pos 1 , => PROADJ
pos -1 NUM pos 0 V pos 1 PROADJ => N
pos -1 ADV pos 0 N pos 1 ADV => V
pos -1 V pos 0 PRO-KS-REL => KS
pos -1 ART pos 0 NUM pos 1 , => N
pos -1 ART pos 0 ADJ pos 1 ADJ => N
pos -1 NPROP pos 0 N pos 1 V => NPROP
pos -1 NPROP pos 0 NUM pos 1 , => N
pos -1 ( pos 0 NUM pos 1 ) => N
pos -1 PROSUB pos 0 N pos 1 ART => V
pos -1 ADV-KS-REL pos 0 N => V
pos 0 KS pos 1 : => ADV
pos -1 ART pos 0 ADJ pos 1 ART => N
pos -1 ) pos 0 N pos 1 ART => V
pos -1 PCP pos 0 PROSUB pos 1 PREP => PREP
pos -1 ADV pos 0 N pos 1 KC => ADJ
pos -1 PDEN pos 0 ADV pos 1 , => PDEN
pos -1 V pos 0 N pos 1 ART => V
pos 0 PREP pos 1 ) => ADV
pos -1 N pos 0 ART pos 1 ADV => PROADJ
pos -1 PREP pos 0 ADJ pos 1 V => N
pos -1 , pos 0 NPROP pos 1 KS => KS
pos -1 KC pos 0 NUM pos 1 . => N
pos -1 NPROP pos 0 N pos 1 ( => NPROP
pos -1 ADJ pos 0 PROSUB pos 1 PREP => PREP
pos -1 PDEN pos 0 ADV pos 1 ART => PDEN
pos 0 NUM pos 1 V => N
pos -1 CUR pos 0 N => NUM
pos -1 V pos 0 NUM pos 1 PREP => N
pos -1 PREP pos 0 ADJ pos 1 ART => ADV
pos -1 ART pos 0 PROADJ pos 1 KC => PROSUB
pos -1 NPROP pos 0 N pos 1 KC => NPROP
pos 0 ART pos 1 PRO-KS => PREP
pos -1 V pos 0 ART pos 1 ADV => ADV
pos -1 PREP pos 0 ADJ pos 1 KC => N
pos -1 NPROP pos 0 NUM pos 1 PREP => N
pos -1 PROADJ pos 0 ADJ pos 1 . => N
pos -1 , pos 0 N pos 1 KS => V
pos -1 , pos 0 PROADJ pos 1 KS => PDEN
pos -1 KC pos 0 PROPESS pos 1 ART => KS
pos -1 PDEN pos 0 N pos 1 N => NUM
pos -1 PDEN pos 0 ADV pos 1 PREP => PDEN
pos -1 NPROP pos 0 N pos 1 N => NPROP
pos -1 NPROP pos 0 N pos 1 ) => NPROP
pos -1 ADJ pos 0 ART pos 1 NUM => PREP
pos -1 ADJ pos 0 PRO-KS-REL pos 1 PREP => KS
pos -1 - pos 0 N pos 1 PROPESS => V
pos 0 PROADJ pos 1 ? => PROSUB
pos -1 N pos 0 N pos 1 ? => ADJ
pos -1 V pos 0 ADV-KS-REL => ADV-KS
pos -1 ART pos 0 NUM pos 1 ADV => N
pos -1 NPROP pos 0 N pos 1 V => NPROP
pos -1 NPROP pos 0 N pos 1 NPROP => NPROP
pos -1 PROADJ pos 0 ART pos 1 . => PROSUB
pos -1 , pos 0 N pos 1 NPROP => NPROP
pos 0 PROADJ pos 1 ) => PROSUB
pos -1 N pos 0 KS pos 1 ART => PRO-KS-REL
pos -1 V pos 0 N pos 1 PROPESS => V
pos -1 PREP pos 0 NUM pos 1 ) => N
pos -1 ART pos 0 ADJ pos 1 PROPESS => N
pos -1 NPROP pos 0 PROSUB pos 1 PREP => PREP
pos -1 PROADJ pos 0 ADJ pos 1 V => N
pos -1 " pos 0 N pos 1 KC => NPROP
pos -1 ; pos 0 N pos 1 , => NPROP
pos -1 V pos 0 NUM pos 1 . => N
pos -1 PREP pos 0 ADJ pos 1 PCP => N
pos -1 PREP pos 0 KS pos 1 NPROP => PRO-KS-REL
pos -1 ART pos 0 ADJ pos 1 PREP => N
pos -1 ART pos 0 ADJ pos 1 ( => N
pos -1 ART pos 0 ADJ pos 1 - => N
pos -1 PROADJ pos 0 ART pos 1 , => PROSUB
pos -1 , pos 0 N pos 1 CUR => V
pos -1 ( pos 0 N pos 1 V => NUM
pos -1 NUM pos 0 V pos 1 ART => N
pos -1 ) pos 0 N pos 1 NPROP => NPROP
pos -1 KS pos 0 N pos 1 ADV => V
pos -1 PCP pos 0 ART pos 1 PROADJ => PREP
pos -1 PCP pos 0 PRO-KS-REL => KS
pos -1 ADV pos 0 N pos 1 . => ADJ
pos -1 ADV pos 0 N pos 1 PROPESS => V
pos -1 ADV pos 0 N pos 1 PROSUB => V
pos -1 PDEN pos 0 NUM pos 1 PREP => N
pos -1 PROSUB pos 0 ADV pos 1 , => N
pos -1 - pos 0 N pos 1 ART => V
pos -1 : pos 0 NPROP pos 1 ! => ADV
pos -1 : pos 0 ADV pos 1 N => N
pos -1 : pos 0 PROPESS pos 1 ART => KS
pos -1 N pos 0 N pos 1 CUR => V
pos -1 N pos 0 N pos 1 NUM => NUM
pos -1 V pos 0 PROPESS pos 1 PROPESS => KS
pos -1 PREP pos 0 NUM pos 1 , => N
pos -1 PREP pos 0 PROADJ pos 1 KC => PROSUB
pos -1 PREP pos 0 ADJ pos 1 PRO-KS-REL => N
pos -1 ART pos 0 ADJ pos 1 ? => N
pos -1 , pos 0 N pos 1 : => V
pos -1 ( pos 0 N pos 1 PROPESS => V
pos -1 ( pos 0 NUM pos 1 , => N
pos -1 PCP pos 0 N pos 1 NPROP => NPROP
pos 0 VAUX pos 1 KS => V
pos -1 N pos 0 PROSUB pos 1 PRO-KS-REL => PREP
pos -1 NPROP pos 0 N pos 1 ART => V
pos -1 PROADJ pos 0 ADJ pos 1 , => N
pos -1 KC pos 0 PRO-KS-REL pos 1 , => KS
pos -1 ( pos 0 N pos 1 ART => V
pos -1 " pos 0 N pos 1 PRO-KS-REL => V
pos -1 V pos 0 PRO-KS-REL => KS
pos -1 " pos 0 N pos 1 PROPESS => V
pos -1 PROSUB pos 0 KS pos 1 PROSUB => PRO-KS-REL
pos -1 / pos 0 N pos 1 ) => NPROP
pos 0 PROADJ pos 1 ( => PROSUB
pos 0 VAUX pos 1 " => V
pos 0 VAUX pos 1 ? => V
pos -1 N pos 0 N pos 1 ... => ADJ
pos -1 N pos 0 ART pos 1 PROSUB => PREP
pos -1 V pos 0 PROADJ pos 1 / => NPROP
pos -1 PREP pos 0 PROSUB pos 1 N => PROADJ
pos -1 NUM pos 0 ADJ pos 1 PREP => N
pos -1 ART pos 0 ADV pos 1 . => N
pos -1 NPROP pos 0 NUM pos 1 NPROP => NPROP
pos -1 NPROP pos 0 NUM pos 1 . => NPROP
pos -1 NPROP pos 0 NPROP pos 1 ADJ => N
pos -1 PROADJ pos 0 PCP pos 1 , => N
pos -1 PROADJ pos 0 ADV pos 1 KS => PROADJ
pos -1 , pos 0 N pos 1 ADV => V
pos -1 ADJ pos 0 ART pos 1 PROSUB => PREP
pos -1 ADJ pos 0 PROPESS pos 1 ART => KS
pos -1 ADJ pos 0 PROSUB pos 1 . => ADV
pos -1 KC pos 0 PROADJ pos 1 NPROP => NPROP
pos -1 VAUX pos 0 VAUX pos 1 PDEN => V
pos -1 KS pos 0 PREP pos 1 V => PROPESS
pos -1 KS pos 0 PREP pos 1 VAUX => PROPESS
pos -1 PROPESS pos 0 N => NUM
pos -1 PDEN pos 0 PROPESS pos 1 PROPESS => KS
pos -1 PRO-KS pos 0 PRO-KS pos 1 , => PRO-KS-REL
pos -1 ' pos 0 ART pos 1 NPROP => NPROP
pos 0 ART pos 1 ) => N
pos 0 PROADJ pos 1 ! => PROSUB
pos -1 V pos 0 PROSUB pos 1 NPROP => NPROP
pos -1 PREP pos 0 NUM pos 1 KC => N
pos -1 PREP pos 0 ADV-KS-REL => ADV-KS
pos -1 ART pos 0 V pos 1 ADJ => N
pos -1 ART pos 0 PROADJ pos 1 KS => PROSUB
pos -1 NPROP pos 0 ADV pos 1 NPROP => NPROP
pos -1 PROADJ pos 0 NUM pos 1 PREP => N
pos -1 PROADJ pos 0 NUM pos 1 , => N
pos -1 , pos 0 N pos 1 PROSUB => V
pos -1 , pos 0 NUM pos 1 KC => N
pos -1 , pos 0 NUM pos 1 ; => N
pos -1 , pos 0 ADV pos 1 CUR => KC
pos -1 , pos 0 PROPESS pos 1 PCP => KS
pos -1 KC pos 0 PRO-KS-REL pos 1 PREP => KS
pos -1 KC pos 0 ADV pos 1 NUM => PROADJ
pos -1 ( pos 0 NUM pos 1 PREP => N
pos -1 ( pos 0 ART pos 1 NUM => PREP
pos -1 PCP pos 0 NPROP pos 1 KS => KS
pos -1 NPROP pos 0 KS pos 1 ADV => PRO-KS-REL
pos -1 ADV pos 0 N pos 1 ) => ADJ
pos -1 ADV pos 0 N pos 1 ! => V
pos -1 ADV pos 0 ART pos 1 ADV => ADV
pos -1 PROSUB pos 0 PREP pos 1 KC => ADJ
pos -1 PRO-KS pos 0 PREP pos 1 V => PROPESS
pos -1 ... pos 0 N pos 1 ART => V
pos 0 PROADJ pos 1 PDEN => PROSUB
pos 0 PROADJ pos 1 ... => PROSUB
pos 0 VAUX pos 1 CUR => V
pos 0 VAUX pos 1 KC => V
pos 0 KS pos 1 . => ADV
pos -1 N pos 0 N pos 1 PRO-KS-REL => ADJ
pos -1 N pos 0 N pos 1 PDEN => ADJ
pos -1 N pos 0 ART pos 1 NUM => PREP
pos -1 V pos 0 NPROP pos 1 KS => KS
pos -1 V pos 0 VAUX => V
pos -1 PREP pos 0 PREP pos 1 KC => ADV
pos -1 PREP pos 0 PREP pos 1 PDEN => PDEN
pos -1 PREP pos 0 ADJ pos 1 ADJ => N
pos -1 PREP pos 0 ADJ pos 1 ADV => N
pos -1 ART pos 0 ADV pos 1 NPROP => ADJ
pos -1 NPROP pos 0 N pos 1 N => NPROP
pos -1 NPROP pos 0 NUM pos 1 " => NPROP
pos -1 PROADJ pos 0 ADJ pos 1 ADV => N
pos -1 , pos 0 PROPESS pos 1 PREP => KS
pos -1 , pos 0 PROPESS pos 1 NPROP => KS
pos -1 KC pos 0 ADV pos 1 KS => KS
pos -1 ( pos 0 NUM pos 1 V => N
pos -1 ) pos 0 N pos 1 ADV => V
pos -1 KS pos 0 N pos 1 " => V
pos -1 KS pos 0 PRO-KS-REL => KS
pos -1 " pos 0 N pos 1 - => NPROP
pos -1 " pos 0 V pos 1 NPROP => NPROP
pos -1 " pos 0 NPROP pos 1 N => N
pos -1 NPROP pos 0 N pos 1 VAUX => NPROP
pos -1 NPROP pos 0 N pos 1 . => NPROP
pos -1 ADV pos 0 N pos 1 V => V
pos -1 ADV pos 0 N pos 1 PROADJ => V
pos -1 V pos 0 PROADJ pos 1 . => PROSUB
pos -1 PDEN pos 0 N pos 1 ADV => V
pos -1 PDEN pos 0 ADV pos 1 PROSUB => PROADJ
pos -1 PROSUB pos 0 PREP pos 1 PCP => ADJ
pos -1 - pos 0 NUM pos 1 PREP => N
pos -1 - pos 0 NPROP pos 1 KS => KS
pos -1 - pos 0 PROPESS pos 1 ART => KS
pos -1 : pos 0 ADJ pos 1 PREP => N
pos -1 ; pos 0 PREP pos 1 KS => KS
pos 0 VAUX pos 1 : => V
pos -1 PREP pos 0 VAUX pos 1 VAUX => N
pos -1 PREP pos 0 PCP pos 1 ADJ => N
pos -1 PREP pos 0 PRO-KS pos 1 NPROP => PRO-KS-REL
pos -1 NUM pos 0 ADJ pos 1 KC => N
pos -1 ART pos 0 NUM pos 1 PRO-KS-REL => N
pos -1 ART pos 0 PROADJ pos 1 - => PROSUB
pos -1 ART pos 0 PROADJ pos 1 : => PROSUB
pos -1 ART pos 0 ADJ pos 1 ) => N
pos -1 ART pos 0 ADJ pos 1 PCP => N
pos -1 ART pos 0 ADJ pos 1 ; => N
pos -1 ART pos 0 ADV pos 1 , => N
pos -1 NPROP pos 0 N pos 1 - => NPROP
pos -1 NPROP pos 0 N pos 1 ? => NPROP
pos -1 NPROP pos 0 ART pos 1 PROSUB => PREP
pos -1 NPROP pos 0 KS pos 1 VAUX => PRO-KS-REL
pos -1 NPROP pos 0 PROPESS pos 1 NPROP => NPROP
pos -1 NPROP pos 0 PDEN pos 1 NPROP => NPROP
pos -1 NPROP pos 0 PRO-KS => PRO-KS-REL
pos -1 PROADJ pos 0 PCP pos 1 V => N
pos -1 PROADJ pos 0 ADV pos 1 PREP => PROADJ
pos -1 N pos 0 PROADJ pos 1 ADV => ADV
pos -1 , pos 0 ADJ pos 1 PRO-KS-REL => N
pos -1 , pos 0 ADJ pos 1 ) => N
pos -1 , pos 0 PROSUB pos 1 . => PDEN
pos -1 ADJ pos 0 ART pos 1 NPROP => PREP
pos -1 KC pos 0 N pos 1 PROPESS => V
pos -1 KC pos 0 PRO-KS-REL pos 1 " => KS
pos -1 ( pos 0 PREP pos 1 PDEN => PDEN
pos -1 ( pos 0 ADJ pos 1 PREP => N
pos -1 ) pos 0 N pos 1 PRO-KS-REL => V
pos -1 V pos 0 PRO-KS-REL => KS
pos -1 KS pos 0 N pos 1 NPROP => V
pos -1 KS pos 0 N pos 1 . => V
pos -1 KS pos 0 PROADJ pos 1 PROPESS => PROSUB
pos -1 " pos 0 N pos 1 ADV => V
pos -1 PCP pos 0 PROPESS pos 1 ADV => KS
pos -1 ADV pos 0 N pos 1 ; => V
pos -1 PROPESS pos 0 PROSUB pos 1 ) => PROADJ
pos -1 PDEN pos 0 NUM pos 1 . => N
pos -1 PDEN pos 0 ADV pos 1 ADV => PDEN
pos -1 PROSUB pos 0 N pos 1 PREP => V
pos -1 PROSUB pos 0 NPROP pos 1 KS => KS
pos -1 PROSUB pos 0 KS pos 1 ART => PRO-KS-REL
pos -1 PROSUB pos 0 KS pos 1 PROADJ => PRO-KS-REL
pos -1 : pos 0 ADV pos 1 ADJ => PROADJ
pos -1 ; pos 0 N pos 1 : => NPROP
pos -1 ; pos 0 NPROP pos 1 ADJ => N
pos -1 ; pos 1 ) => N
pos -1 IN pos 0 N pos 1 NPROP => NPROP
pos -1 ... pos 0 N pos 1 , => ADJ
pos 0 VAUX pos 1 PRO-KS => V
pos -1 N pos 0 N pos 1 PROADJ => V
pos -1 N pos 0 PREP pos 1 ! => N
pos -1 N pos 0 ART pos 1 , => N
pos -1 N pos 0 ART pos 1 ... => N
pos -1 N pos 0 NPROP pos 1 ADJ => N
pos -1 V pos 0 NUM pos 1 ART => N
pos -1 V pos 0 PROADJ pos 1 . => PROSUB
pos -1 V pos 0 PROADJ pos 1 : => PROSUB
pos -1 V pos 0 KC pos 1 . => ADV
pos -1 V pos 0 PROPESS pos 1 VAUX => KS
pos -1 PREP pos 0 V pos 1 ADV-KS => N
pos -1 PREP pos 0 NUM pos 1 . => N
pos -1 PREP pos 0 NUM pos 1 ADV => N
pos -1 PREP pos 0 PROADJ pos 1 KS => PROSUB
pos -1 PREP pos 0 PROADJ pos 1 : => PROSUB
pos -1 PREP pos 0 ADJ pos 1 ? => N
pos -1 PREP pos 0 KC pos 1 N => PROADJ
pos -1 PREP pos 0 KC pos 1 , => PROSUB
pos -1 PREP pos 0 VAUX pos 1 PROPESS => V
pos -1 PREP pos 0 KS pos 1 ? => PROSUB
pos -1 PREP pos 0 ADV pos 1 PROSUB => PROADJ
pos -1 PREP pos 0 PROSUB pos 1 ADJ => ART
pos -1 PREP pos 0 ADV-KS pos 1 VAUX => ADV
pos -1 NUM pos 0 NPROP pos 1 PREP => N
pos -1 NUM pos 0 ADJ pos 1 PRO-KS-REL => N
pos -1 NUM pos 0 ADJ pos 1 VAUX => N
pos -1 ART pos 0 NUM pos 1 PROPESS => N
pos -1 ART pos 0 ADJ pos 1 KS => N
pos -1 ART pos 0 ADJ pos 1 ... => N
pos -1 ART pos 0 ADV pos 1 KC => N
pos -1 ART pos 0 ADV pos 1 KS => PROADJ
pos -1 ART pos 0 PROSUB pos 1 N => PROADJ
pos -1 NPROP pos 0 N pos 1 CUR => NPROP
pos -1 NPROP pos 0 KS pos 1 , => PRO-KS-REL
pos -1 NPROP pos 0 PROPESS pos 1 PROPESS => KS
pos -1 NPROP pos 0 ? pos 1 ? => NPROP
pos -1 PROADJ pos 0 V pos 1 PROSUB => N
pos -1 PROADJ pos 0 PREP pos 1 PROPESS => PROSUB
pos -1 PROADJ pos 0 PROADJ pos 1 PROSUB => PROSUB
pos -1 PROADJ pos 0 NUM pos 1 . => N
pos -1 PROADJ pos 0 ADJ pos 1 ADJ => N
pos -1 PROADJ pos 0 ADJ pos 1 VAUX => N
pos -1 , pos 0 PRO-KS pos 1 PRO-KS-REL => PRO-KS-REL
pos -1 PRO-KS-REL pos 0 V pos 1 ! => N
pos -1 , pos 0 PRO-KS-REL pos 1 N => PROADJ
pos -1 PRO-KS-REL pos 0 N => V
pos -1 PRO-KS-REL pos 0 ADJ pos 1 V => ADV
pos -1 PRO-KS-REL pos 0 ADJ pos 1 ART => V
pos -1 ADJ pos 0 NPROP pos 1 : => N
pos -1 ADJ pos 0 PRO-KS-REL pos 1 NUM => KS
pos -1 ADJ pos 0 PRO-KS-REL pos 1 " => KS
pos -1 KC pos 0 N pos 1 ... => NPROP
pos -1 KC pos 0 PREP pos 1 PCP => ADV
pos -1 KC pos 0 NUM pos 1 ) => N
pos -1 ( pos 0 KC pos 1 PDEN => PDEN
pos -1 ( pos 0 PROPESS pos 1 PROADJ => KS
pos -1 ) pos 0 N pos 1 PROPESS => V
pos -1 ) pos 0 NPROP pos 1 N => N
pos -1 ) pos 0 NPROP pos 1 KS => KS
pos -1 ) pos 0 PRO-KS => PROSUB
pos -1 KS pos 0 N pos 1 PRO-KS-REL => V
pos -1 V pos 0 PRO-KS-REL => KS
pos -1 KS pos 0 NUM pos 1 PREP => N
pos -1 KS pos 0 ART pos 1 . => PROSUB
pos -1 KS pos 0 PROADJ pos 1 PCP => PROSUB
pos -1 KS pos 0 PROPESS pos 1 ART => KS
pos -1 " pos 0 PROADJ pos 1 PROSUB => NPROP
pos -1 " pos 0 PROPESS pos 1 ART => KS
pos -1 PCP pos 0 N pos 1 " => ADJ
pos -1 " pos 0 PCP pos 1 ADJ => N
pos -1 PCP pos 0 ART pos 1 PROSUB => PREP
pos -1 PCP pos 0 ADV pos 1 KS => KS
pos -1 PCP pos 0 PROPESS pos 1 PROADJ => KS
pos -1 KS pos 0 PROADJ pos 1 V => PROSUB
pos -1 ADV pos 0 N pos 1 PDEN => ADJ
pos -1 ADV pos 0 NUM pos 1 PREP => N
pos -1 ADV pos 0 ADV pos 1 ) => PROADJ
pos -1 ADV pos 0 PROPESS pos 1 ART => KS
pos -1 ADV pos 0 PROSUB pos 1 , => ADV
pos -1 PROPESS pos 0 ART pos 1 ADV => ADV
pos -1 PROPESS pos 0 NPROP pos 1 KS => KS
pos -1 PDEN pos 0 ART pos 1 , => PROSUB
pos -1 PDEN pos 0 ART pos 1 ADV => ADV
pos -1 PDEN pos 0 ADV pos 1 NUM => PROADJ
pos -1 PDEN pos 0 PROPESS pos 1 ART => KS
pos -1 PROSUB pos 0 N pos 1 PRO-KS-REL => V
pos -1 V pos 0 PRO-KS-REL pos 1 ART => KS
pos -1 PROSUB pos 0 N pos 1 KC => ADJ
pos -1 PROSUB pos 0 PREP pos 1 VAUX => PROSUB
pos -1 KS pos 0 PROSUB pos 1 PROSUB => PROADJ
pos -1 PROSUB pos 0 PREP pos 1 - => N
pos -1 PROSUB pos 0 KS pos 1 ART => PRO-KS-REL
pos -1 PROSUB pos 0 PROSUB => PREP
pos -1 - pos 0 ADV pos 1 KS => KS
pos -1 : pos 0 NUM pos 1 PREP => N
pos -1 : pos 0 PRO-KS-REL => KS
pos -1 : pos 0 ADV pos 1 KS => KS
pos -1 PRO-KS pos 0 ADJ => ADV
pos -1 PRO-KS pos 0 PRO-KS pos 1 ADV => PRO-KS-REL
pos -1 V pos 0 PRO-KS pos 1 PRO-KS-REL => PROSUB
pos -1 PRO-KS pos 0 PRO-KS-REL => PRO-KS
pos -1 ; pos 0 N pos 1 NPROP => NPROP
pos -1 ; pos 0 NPROP pos 1 PREP => N
pos -1 ' pos 0 N pos 1 N => NPROP
pos -1 N pos 0 N pos 1 ' => V
pos -1 NPROP pos 0 N pos 1 V => NPROP
pos 0 . pos 1 NPROP => NPROP
pos 0 VAUX pos 1 ! => V
pos 0 PROPESS pos 1 PROSUB => KS
pos 0 ADV-KS pos 1 NPROP => ADV-KS-REL
pos -1 N pos 0 ART pos 1 . => PROPESS
pos -1 N pos 0 ART pos 1 : => N
pos -1 N pos 0 PRO-KS-REL pos 1 NUM => KS
pos -1 N pos 0 PROSUB pos 1 PRO-KS-REL => PRO-KS
pos -1 N pos 0 N pos 1 PRO-KS => V
pos -1 N pos 0 PROSUB pos 1 ? => ADJ
pos -1 N pos 0 PRO-KS pos 1 PRO-KS-REL => PROADJ
pos -1 N pos 0 ADV-KS => KS
pos -1 N pos 0 IN pos 1 NPROP => NPROP
pos -1 NPROP pos 0 N pos 1 NPROP => NPROP
pos -1 V pos 0 N pos 1 CUR => PCP
pos -1 V pos 0 NUM pos 1 ) => N
pos -1 V pos 0 NUM pos 1 " => NPROP
pos -1 " pos 0 V pos 1 NPROP => NPROP
pos -1 V pos 0 ART pos 1 ... => PROSUB
pos -1 V pos 0 ADJ pos 1 PCP => ADV
pos -1 V pos 0 KC pos 1 : => ADV
pos -1 V pos 0 KC pos 1 ! => ADV
pos -1 V pos 0 PCP pos 1 PREP => N
pos -1 PREP pos 0 V pos 1 PCP => VAUX
pos -1 PREP pos 0 PREP pos 1 ... => N
pos -1 PREP pos 0 NUM pos 1 KS => N
pos -1 PREP pos 0 NUM pos 1 " => N
pos -1 PREP pos 0 NUM pos 1 - => N
pos -1 PREP pos 0 NUM pos 1 ! => N
pos -1 PREP pos 0 PROADJ pos 1 ADV-KS-REL => PROSUB
pos -1 PREP pos 0 PRO-KS-REL pos 1 VAUX => PRO-KS
pos -1 PREP pos 0 ADJ pos 1 PREP => ADV
pos -1 PREP pos 0 ADJ pos 1 KS => N
pos -1 PREP pos 0 ADJ pos 1 PROPESS => ADV
pos -1 PRO-KS pos 0 PREP pos 1 ADV => ADV
pos -1 PREP pos 0 ADJ pos 1 PROSUB => N
pos -1 N pos 0 PROSUB pos 1 PDEN => PDEN
pos -1 PREP pos 0 ADJ pos 1 - => ADV
pos -1 PREP pos 0 ADJ pos 1 : => ADV
pos -1 PREP pos 0 ADJ pos 1 ; => N
pos -1 PREP pos 0 KS pos 1 KC => PRO-KS-REL
pos -1 PREP pos 0 KS pos 1 " => PRO-KS-REL
pos -1 PREP pos 0 PROSUB pos 1 N => ART
pos -1 PREP pos 0 PRO-KS pos 1 ART => PROSUB
pos -1 PREP pos 0 PRO-KS pos 1 . => PROSUB
pos -1 PREP pos 0 PRO-KS pos 1 PROADJ => PRO-KS-REL
pos -1 PREP pos 0 PRO-KS pos 1 KS => PROSUB
pos -1 PREP pos 0 ADV-KS pos 1 PDEN => ADV-KS-REL
pos -1 PREP pos 0 ADV-KS pos 1 PRO-KS => ADV-KS-REL
pos -1 PREP pos 0 ADV-KS pos 1 ? => ADV
pos -1 NUM pos 0 NUM pos 1 NUM => N
pos -1 N pos 0 NUM pos 1 N => N
pos -1 NUM pos 0 ART pos 1 PROADJ => PREP
pos -1 NUM pos 0 PROADJ pos 1 " => PROSUB
pos -1 NUM pos 0 KS pos 1 ADJ => N
pos -1 NUM pos 0 ADV pos 1 PREP => PREP
pos -1 ART pos 0 V pos 1 PREP => VAUX
pos -1 ART pos 0 NUM pos 1 ART => N
pos -1 ART pos 0 NUM pos 1 KS => N
pos -1 ART pos 0 PROADJ pos 1 KS => KS
pos -1 ART pos 0 ADJ pos 1 PROSUB => ADV
pos -1 ART pos 0 ADJ pos 1 ! => N
pos -1 ART pos 0 KS pos 1 N => N
pos -1 ART pos 0 ADV pos 1 ( => N
pos -1 ART pos 0 ADV pos 1 " => N
pos -1 ART pos 0 PDEN pos 1 V => N
pos -1 ART pos 0 PDEN pos 1 : => N
pos -1 ART pos 0 PROSUB pos 1 N => PROADJ
pos -1 ART pos 0 PROSUB pos 1 ADJ => PROADJ
pos -1 NPROP pos 0 N pos 1 NUM => NPROP
pos -1 NPROP pos 0 N pos 1 PROADJ => NPROP
pos -1 NPROP pos 0 N pos 1 PDEN => NPROP
pos -1 NPROP pos 0 N pos 1 ; => NPROP
pos -1 NPROP pos 0 NUM pos 1 ART => N
pos -1 NPROP pos 0 NUM pos 1 ( => NPROP
pos -1 NPROP pos 0 ART pos 1 ' => NPROP
pos -1 NPROP pos 0 PROADJ pos 1 , => PROSUB
pos -1 NPROP pos 0 PRO-KS-REL pos 1 ART => PROSUB
pos -1 NPROP pos 0 VAUX pos 1 PROADJ => V
pos -1 NPROP pos 0 ADV pos 1 " => NPROP
pos -1 NPROP pos 0 PROPESS pos 1 " => NPROP
pos -1 NPROP pos 0 PROSUB pos 1 " => NPROP
pos -1 NPROP pos 0 PROSUB pos 1 ! => PROADJ
pos -1 NPROP pos 0 ADV-KS-REL pos 1 ... => NPROP
pos -1 NPROP pos 0 IN pos 1 NPROP => NPROP
pos -1 . => NPROP
pos -1 NPROP pos 0 . pos 1 NPROP => NPROP
pos -1 PROADJ pos 0 V pos 1 PRO-KS => N
pos -1 N pos 0 PRO-KS pos 1 PRO-KS => PROADJ
pos -1 PROADJ pos 0 NUM pos 1 PREP => N
pos -1 PROADJ pos 0 ART pos 1 KC => PROSUB
pos -1 PROADJ pos 0 NPROP pos 1 ADJ => N
pos -1 PROADJ pos 0 PROADJ pos 1 ART => PROSUB
pos -1 PROADJ pos 0 PRO-KS-REL pos 1 PREP => KS
pos -1 PROPESS pos 0 PROADJ pos 1 PRO-KS-REL => PROSUB
pos -1 , pos 0 PROPESS pos 1 PROADJ => KS
pos -1 PROADJ pos 0 PRO-KS-REL => ADV
pos -1 PROADJ pos 0 ADJ pos 1 . => N
pos -1 PROADJ pos 0 ADJ pos 1 , => N
pos -1 PROADJ pos 0 ADJ pos 1 PRO-KS-REL => N
pos -1 PROADJ pos 0 ADJ pos 1 KS => N
pos -1 PROADJ pos 0 ADJ pos 1 ? => N
pos -1 PROADJ pos 0 PCP pos 1 VAUX => N
pos -1 PROADJ pos 0 PROSUB pos 1 PDEN => PROADJ
pos -1 PROADJ pos 0 PRO-KS => PRO-KS-REL
pos -1 , pos 0 N pos 1 PROADJ => V
pos -1 , pos 0 V pos 1 PCP => VAUX
pos -1 , pos 0 NUM pos 1 PREP => N
pos -1 , pos 0 NUM pos 1 ADV => N
pos -1 , pos 0 NUM pos 1 PROSUB => PREP
pos -1 , pos 0 ART pos 1 KS => KS
pos -1 , pos 0 NPROP pos 1 PRO-KS-REL => KS
pos -1 KS pos 0 PRO-KS-REL => KS
pos -1 , pos 0 PROADJ pos 1 V => PROSUB
pos -1 , pos 0 , pos 1 PROSUB => PDEN
pos -1 , pos 0 ADJ pos 1 " => N
pos -1 , pos 0 PCP pos 1 KS => KS
pos -1 , pos 0 PROSUB pos 1 ART => PROADJ
pos -1 , pos 0 PRO-KS pos 1 KS => PREP
pos -1 , pos 0 IN pos 1 PROSUB => N
pos -1 PRO-KS-REL pos 0 PREP pos 1 KS => KS
pos -1 PRO-KS-REL pos 0 PREP pos 1 PCP => VAUX
pos -1 PRO-KS-REL pos 0 ADJ pos 1 PREP => V
pos -1 PRO-KS-REL pos 0 KC pos 1 ADJ => ADV
pos -1 PREP pos 0 PRO-KS-REL pos 1 KC => PRO-KS
pos -1 PRO-KS-REL pos 0 VAUX pos 1 PDEN => V
pos -1 PRO-KS-REL pos 0 PROPESS pos 1 ART => KS
pos -1 PRO-KS-REL pos 0 PROSUB pos 1 PRO-KS-REL => PRO-KS
pos -1 PRO-KS pos 0 PRO-KS-REL => PRO-KS
pos -1 ADJ pos 0 N pos 1 NPROP => NPROP
pos -1 ADJ pos 0 N pos 1 PROADJ => V
pos -1 KS pos 0 ADJ pos 1 V => N
pos -1 V pos 0 PROADJ pos 1 , => PROSUB
pos -1 ADJ pos 0 ART pos 1 KS => PROADJ
pos -1 ADJ pos 0 NPROP pos 1 ADJ => N
pos -1 ADJ pos 0 PRO-KS-REL pos 1 ART => KS
pos -1 ADJ pos 0 PRO-KS-REL pos 1 ADJ => KS
pos -1 ADJ pos 0 PRO-KS-REL pos 1 KS => KS
pos -1 ADJ pos 0 PCP pos 1 VAUX => N
pos -1 ADJ pos 0 ADV pos 1 PROSUB => KC
pos -1 ADJ pos 0 PROPESS pos 1 PCP => KS
pos -1 ADJ pos 0 PROSUB pos 1 , => PROADJ
pos -1 ADJ pos 0 PROSUB pos 1 ) => PDEN
pos -1 ADJ pos 0 PROSUB pos 1 ! => ADV
pos -1 KC pos 0 N pos 1 CUR => NUM
pos -1 KC pos 0 NUM pos 1 PREP => N
pos -1 KC pos 0 NUM pos 1 ( => N
pos -1 KC pos 0 ART pos 1 VAUX => PROPESS
pos -1 KC pos 0 PROPESS pos 1 PREP => KS
pos -1 KS pos 0 PREP pos 1 V => PROPESS
pos -1 KC pos 0 PROPESS pos 1 PROADJ => KS
pos -1 KC pos 0 PRO-KS pos 1 VAUX => PROSUB
pos -1 VAUX pos 0 VAUX pos 1 PROPESS => V
pos -1 VAUX pos 0 VAUX pos 1 ADV-KS-REL => V
pos -1 V pos 0 ADV-KS-REL => ADV-KS
pos -1 V pos 0 ADV-KS pos 1 NPROP => ADV-KS-REL
pos -1 VAUX pos 0 PCP pos 1 PRO-KS => NPROP
pos -1 NPROP pos 0 PRO-KS => PRO-KS-REL
pos -1 , pos 0 VAUX pos 1 NPROP => V
pos -1 ( pos 0 N pos 1 NUM => NUM
pos -1 ( pos 0 V pos 1 PROSUB => N
pos -1 ( pos 0 PREP pos 1 VAUX => KS
pos -1 ( pos 0 PREP pos 1 KS => KS
pos -1 ( pos 0 ART pos 1 KS => KS
pos -1 ART pos 0 KS => PROSUB
pos -1 ( pos 0 PROADJ pos 1 PROSUB => PDEN
pos -1 ( pos 0 VAUX pos 1 PCP => V
pos -1 V pos 0 PCP pos 1 V => N
pos -1 ( pos 0 ADV-KS-REL pos 1 PROSUB => KS
pos -1 ) pos 0 N pos 1 PROADJ => V
pos -1 V pos 0 PROADJ pos 1 . => PROSUB
pos -1 ) pos 0 PREP pos 1 : => PROSUB
pos -1 ) pos 0 NPROP pos 1 PREP => N
pos -1 ) pos 0 NPROP pos 1 PRO-KS-REL => KS
pos -1 ) pos 0 PROADJ pos 1 V => PROSUB
pos -1 ) pos 0 PRO-KS-REL pos 1 PREP => KS
pos -1 KS pos 0 N pos 1 PROADJ => V
pos -1 V pos 0 PROADJ pos 1 . => PROSUB
pos -1 KS pos 0 N pos 1 PRO-KS => V
pos -1 KS pos 0 V pos 1 ? => N
pos -1 KS pos 0 PREP pos 1 KS => ADV
pos -1 KS pos 0 PREP pos 1 PDEN => ADV
pos -1 KS pos 0 PREP pos 1 ? => V
pos -1 KS pos 0 NUM pos 1 PREP => N
pos -1 KS pos 0 PROADJ pos 1 PREP => PROSUB
pos -1 KS pos 0 PROADJ pos 1 KC => PROSUB
pos -1 - pos 0 KS pos 1 PROSUB => PRO-KS-REL
pos -1 KS pos 0 PROADJ pos 1 ADV => PROSUB
pos -1 KS pos 0 PRO-KS-REL => KS
pos -1 KS pos 0 ADJ pos 1 PROPESS => ADV
pos -1 NPROP pos 0 KS pos 1 ADV => PRO-KS-REL
pos -1 KS pos 0 KC pos 1 ADJ => KS
pos -1 KS pos 0 VAUX pos 1 ( => V
pos -1 KS pos 0 KS pos 1 , => PRO-KS-REL
pos -1 N pos 0 KS pos 1 PRO-KS-REL => NPROP
pos -1 V pos 0 KS pos 1 PRO-KS-REL => NPROP
pos -1 KS pos 0 PRO-KS-REL => KS
pos -1 KS pos 0 PROPESS pos 1 NPROP => KS
pos -1 KS pos 0 PROPESS pos 1 PCP => KS
pos -1 KS pos 0 PROSUB pos 1 ART => PROADJ
pos -1 KS pos 0 PROSUB pos 1 ... => PROADJ
pos -1 KS pos 0 ADV-KS-REL => ADV-KS
pos -1 " pos 0 PREP pos 1 ADV-KS => ADV
pos -1 " pos 0 NUM pos 1 " => N
pos -1 " pos 0 ART pos 1 " => N
pos -1 " pos 0 NPROP pos 1 N => V
pos -1 " pos 0 NPROP pos 1 PRO-KS-REL => KS
pos -1 " pos 0 PROADJ pos 1 V => PROSUB
pos -1 " pos 0 ADJ pos 1 NPROP => NPROP
pos -1 " pos 0 PROSUB pos 1 . => PDEN
pos -1 " pos 0 PROSUB pos 1 ... => ADV
pos -1 " pos 0 ADV-KS-REL => ADV
pos -1 PCP pos 0 N pos 1 N => NUM
pos -1 PCP pos 0 N pos 1 PROPESS => V
pos -1 PCP pos 0 NUM pos 1 , => N
pos -1 PCP pos 0 ART pos 1 V => PREP
pos -1 PCP pos 0 ART pos 1 ADV => ADV
pos -1 PCP pos 0 ART pos 1 PROSUB => ADV
pos -1 PCP pos 0 NPROP pos 1 N => N
pos -1 PCP pos 0 NPROP pos 1 ADJ => N
pos -1 PCP pos 0 PROADJ pos 1 NPROP => NPROP
pos -1 PCP pos 0 PROADJ pos 1 PROSUB => PROSUB
pos -1 PCP pos 0 ADJ pos 1 NPROP => N
pos -1 PCP pos 0 PROPESS pos 1 VAUX => KS
pos -1 PCP pos 0 PROSUB pos 1 ) => PDEN
pos -1 PCP pos 0 PROSUB pos 1 " => NPROP
pos -1 PCP pos 0 PROSUB pos 1 ADV => PROADJ
pos -1 ADV pos 0 N pos 1 ART => V
pos -1 ADV pos 0 N pos 1 KS => ADJ
pos -1 N pos 0 KS pos 1 PROSUB => PRO-KS-REL
pos -1 N pos 0 N pos 1 PRO-KS-REL => NPROP
pos -1 NPROP pos 0 PRO-KS-REL pos 1 PROSUB => KS
pos -1 ADV pos 0 PREP pos 1 KC => ADV
pos -1 ADV pos 0 PREP pos 1 KS => KS
pos -1 ADV pos 0 PROADJ pos 1 KS => PDEN
pos -1 ADV pos 0 KS pos 1 ADJ => ADV
pos -1 ADV pos 0 ADV pos 1 ... => PROADJ
pos -1 ADV pos 0 PDEN pos 1 PDEN => KC
pos -1 ADV pos 0 PROSUB pos 1 , => PDEN
pos -1 ADV pos 0 PROSUB pos 1 KS => ADV
pos -1 ADV pos 0 ADV-KS => ADV
pos -1 PROPESS pos 0 ART pos 1 PROADJ => PREP
pos -1 PROPESS pos 0 VAUX pos 1 PREP => V
pos -1 PROPESS pos 0 KS pos 1 PCP => PRO-KS-REL
pos -1 PRO-KS-REL pos 0 PCP pos 1 . => V
pos -1 PROPESS pos 0 KS pos 1 ' => PRO-KS-REL
pos -1 PROPESS pos 0 ADV pos 1 : => KS
pos -1 PROPESS pos 0 PRO-KS pos 1 PROPESS => PRO-KS-REL
pos -1 PDEN pos 0 N pos 1 PROPESS => V
pos -1 PDEN pos 0 PREP pos 1 KS => KS
pos -1 PREP pos 0 PDEN pos 1 KS => N
pos -1 PDEN pos 0 NUM pos 1 , => N
pos -1 PDEN pos 0 ART pos 1 . => PROSUB
pos -1 PDEN pos 0 NPROP pos 1 KS => KS
pos -1 PDEN pos 0 KC pos 1 PROSUB => PDEN
pos -1 PDEN pos 0 ADV pos 1 PROADJ => PDEN
pos -1 PDEN pos 0 PROPESS pos 1 ADV => KS
pos -1 PROSUB pos 0 N pos 1 . => V
pos -1 PROSUB pos 0 N pos 1 , => ADV
pos -1 PROADJ pos 0 PROSUB pos 1 ADV => PROADJ
pos -1 PROADJ pos 0 ADV pos 1 , => N
pos -1 PROADJ pos 0 PROADJ pos 1 ADV => PDEN
pos -1 PREP pos 0 PROADJ pos 1 PDEN => PROSUB
pos -1 PROADJ pos 0 PDEN pos 1 ADV => PROSUB
pos -1 KS pos 0 PROSUB pos 1 N => NPROP
pos -1 NPROP pos 0 N pos 1 " => NPROP
pos -1 PROSUB pos 0 V pos 1 PRO-KS-REL => N
pos -1 PDEN pos 0 PROSUB pos 1 N => PROADJ
pos -1 PROSUB pos 0 PREP pos 1 PDEN => ADJ
pos -1 PREP pos 0 PROSUB pos 1 ADJ => ART
pos -1 ART pos 0 PROSUB pos 1 ADJ => PROADJ
pos -1 PROADJ pos 0 ADJ pos 1 PDEN => N
pos -1 PROSUB pos 0 PREP pos 1 ? => N
pos -1 ART pos 0 PROSUB pos 1 N => PROADJ
pos -1 PROSUB pos 0 PREP pos 1 ! => PDEN
pos -1 PROSUB pos 0 PRO-KS-REL pos 1 KC => PROSUB
pos -1 PROSUB pos 0 PRO-KS-REL pos 1 KS => PROSUB
pos -1 PROSUB pos 0 KC pos 1 PDEN => PRO-KS
pos -1 PROSUB pos 0 PCP pos 1 NPROP => NPROP
pos -1 " pos 0 PROSUB pos 1 NPROP => NPROP
pos -1 PROSUB pos 0 ADV pos 1 ; => N
pos -1 PREP pos 0 PROSUB pos 1 N => PROADJ
pos -1 PROSUB pos 0 PROPESS pos 1 ART => KS
pos -1 PROSUB pos 0 PROPESS pos 1 PROADJ => KS
pos -1 KS pos 0 PROADJ pos 1 V => PROSUB
pos -1 PROSUB pos 0 PDEN pos 1 : => N
pos -1 PROSUB pos 0 PROSUB pos 1 PRO-KS-REL => PRO-KS
pos -1 - pos 0 N pos 1 ) => NPROP
pos -1 - pos 0 N pos 1 PDEN => V
pos -1 - pos 0 NUM pos 1 . => N
pos -1 - pos 0 NUM pos 1 , => N
pos -1 - pos 0 ADV pos 1 . => PREP
pos -1 : pos 0 NPROP pos 1 PROSUB => N
pos -1 : pos 0 PROADJ pos 1 PROSUB => NPROP
pos -1 : pos 0 ADJ pos 1 KS => ADV
pos -1 : pos 0 KS pos 1 V => PROADJ
pos -1 PROADJ pos 0 V pos 1 KC => N
pos -1 : pos 0 PROADJ pos 1 V => KC
pos -1 : pos 0 KS pos 1 VAUX => PROSUB
pos -1 : pos 0 PROPESS pos 1 PROADJ => KS
pos -1 KS pos 0 PROADJ pos 1 V => PROSUB
pos -1 : pos 0 PRO-KS => PROSUB
pos -1 PROSUB pos 0 PRO-KS pos 1 V => NPROP
pos -1 : pos 0 PROSUB pos 1 NPROP => NPROP
pos -1 PRO-KS pos 0 PRO-KS-REL => PRO-KS
pos -1 PRO-KS pos 0 KC pos 1 V => ADV
pos -1 PRO-KS pos 0 PDEN pos 1 , => V
pos -1 PRO-KS pos 0 PROSUB pos 1 PREP => PROADJ
pos -1 PRO-KS pos 0 PROSUB pos 1 ADJ => PROADJ
pos -1 PRO-KS pos 0 PRO-KS pos 1 PREP => PRO-KS-REL
pos -1 PRO-KS pos 0 PRO-KS pos 1 " => PRO-KS-REL
pos -1 , pos 0 PRO-KS pos 1 PRO-KS-REL => PROSUB
pos -1 " pos 0 PRO-KS pos 1 PRO-KS-REL => NPROP
pos -1 NPROP pos 0 PRO-KS-REL pos 1 " => NPROP
pos -1 PRO-KS pos 0 PRO-KS pos 1 PCP => KS
pos -1 , pos 0 PRO-KS pos 1 KS => KS
pos -1 PRO-KS pos 0 PRO-KS pos 1 : => PRO-KS-REL
pos -1 , pos 0 PRO-KS pos 1 PRO-KS-REL => PRO-KS-REL
pos -1 PRO-KS pos 0 PRO-KS pos 1 ' => PRO-KS-REL
pos -1 , pos 0 PRO-KS pos 1 PRO-KS-REL => PROSUB
pos -1 ADV-KS-REL pos 0 V pos 1 KC => N
pos -1 ADV-KS-REL pos 0 V pos 1 - => N
pos -1 ADV-KS-REL pos 0 PREP pos 1 PROPESS => ART
pos -1 ART pos 0 PROPESS => N
pos -1 ADV-KS-REL pos 0 PROSUB pos 1 PRO-KS-REL => PRO-KS
pos -1 PRO-KS pos 0 PRO-KS-REL => PRO-KS
pos -1 $ pos 0 N pos 1 V => ADJ
pos -1 ; pos 0 N pos 1 ( => NPROP
pos -1 ; pos 0 NPROP pos 1 PCP => N
pos -1 ; pos 0 ADV pos 1 . => PREP
pos -1 ; pos 0 PROPESS pos 1 VAUX => KS
pos -1 ; pos 0 PDEN pos 1 KS => KS
pos -1 ADV-KS pos 0 V pos 1 V => VAUX
pos -1 ' pos 0 PROSUB pos 1 PREP => PREP
pos -1 ... pos 0 N pos 1 NPROP => NPROP
pos -1 ... pos 0 PREP pos 1 PROSUB => PDEN
pos -1 ... pos 0 ART pos 1 PROSUB => KS
pos -1 KS pos 0 PROSUB pos 1 KS => KS
pos -1 PROSUB pos 0 KS pos 1 PROPESS => PRO-KS-REL
pos -1 ... pos 0 VAUX pos 1 PCP => V
pos -1 ... pos 0 PRO-KS => PROSUB
pos -1 = pos 0 N pos 1 V => NUM
pos 0 PREP pos 1 ? => ADV
pos -1 ( pos 0 ADV pos 1 ? => PREP
pos 0 NUM pos 1 : => N
pos 0 NUM pos 1 ? => N
pos 0 VAUX pos 1 ... => V
pos 0 KS pos 1 ? => ADV
